"""fix db

Revision ID: a65f68d33496
Revises: f771a819cf8b
Create Date: 2024-07-23 15:02:05.571345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65f68d33496'
down_revision: Union[str, None] = 'f771a819cf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'books', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('authors', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
