"""ondelete

Revision ID: f771a819cf8b
Revises: d033ae26b666
Create Date: 2024-07-23 13:21:02.477632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f771a819cf8b'
down_revision: Union[str, None] = 'd033ae26b666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('reserv_book_id_fkey', 'reserv', type_='foreignkey')
    op.drop_constraint('reserv_user_id_fkey', 'reserv', type_='foreignkey')
    op.create_foreign_key(None, 'reserv', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'reserv', 'books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserv', type_='foreignkey')
    op.drop_constraint(None, 'reserv', type_='foreignkey')
    op.create_foreign_key('reserv_user_id_fkey', 'reserv', 'user', ['user_id'], ['id'])
    op.create_foreign_key('reserv_book_id_fkey', 'reserv', 'books', ['book_id'], ['id'])
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
